spring.jpa.hibernate.ddl-auto=update
cors.allowed-origins=http://localhost:3003,http://10.2.5.11:3003,http://ui-service:80
external.service.classification.url=http://ai-service:5000/invoke
external.service.resolution.url=http://task-agent:5001/trigger-agent
